#
# docker composes file for hx
# author: wens.wq
#
version: "2"

services:
  # third chain service(ex. btc ltc...)
  hx_thirdchain:
    #build: 
      #context: .
      #dockerfile: Dockerfile_thirdchain
    #image: hx_thirdchain:1.0
    image: zoowii/hxmiddleware_base:latest
    labels:
      author: "wens.wq"
      description: "third chain service for hx"
    tty: true
    ports:
      - 60011:60011
      - 60012:60012
      - 19020:19020
      - 19019:19019
      - 19021:80
    volumes:
      - ./hx:/hx
      #- ./volumes/bitcoin_data:/hx/bitcoin_data
      #- ./volumes/litecoin_data:/hx/litecoin_data
      #- ./volumes/hc_data:/hx/hc_data
      #    networks:
      #app_net:
      #  ipv4_address: 192.168.18.6    

    container_name: third_chain
    entrypoint:
      - /bin/bash
      - -c
      - /hx/start_third_chain.sh



  hx_mainchain:
    #build:
      #context: .
      #dockerfile: Dockerfile_mainchain
    image: zoowii/hxmiddleware_db:latest
    labels:
      author: "wens.wq"
      description: "hx main chain"
    tty: true
    ports:
      - 5005:5005
      - 27017:27017
      - 8090:8090
      - 9034:9034
    volumes:
      - ./hx:/hx
      - ./hx_pgsql_data/formal_data:/var/formal_data
      #- ./volumes/mongo_data:/hx/mongo_data
      #- ./volumes/witness_data:/hx/witness_data
      #- ./volumes/logs:/hx/logs
    depends_on:
      - hx_thirdchain
    links:
      - hx_thirdchain:wallet_host
      - hx_thirdchain:btc_wallet
      - hx_thirdchain:ltc_wallet
      #- hx_thirdchain:eth_wallet
      # - hx_thirdchain:hc_wallet
    extra_hosts:
      #- "wallet_host:172.24.2.77"
      - "eth_wallet:${WALLET_HOST}"
      - "hc_wallet:${WALLET_HOST}"
      - "chaindb:127.0.0.1"
    # networks:
    #  app_net:
    #    ipv4_address: 192.168.18.8

    container_name: main_chain
    entrypoint:
      - /bin/bash
      - -c
      - /hx/start_main_chain.sh


    # networks: 
    #app_net:
    # driver: bridge
    # ipam:
    #  driver: default
    #  config:
    #  - subnet: 192.168.18.0/16











  




