FROM zoowii/hxmiddleware_base

#
# docker metainfo
#
LABEL author="wens.wq"
LABEL description="docker file for hx environment"
LABEL version="1.0"

#
# data preparation
# 
RUN  mkdir -p /hx
COPY third_chain/bitcoind  /hx
COPY third_chain/litecoind /hx
COPY third_chain/start.sh  /hx
COPY third_chain/hcd /hx
COPY third_chain/hcwallet /hx
RUN  chmod +x  /hx/bitcoind  /hx/litecoind /hx/start.sh /hx/hcd /hx/hcwallet
RUN  ln -s /hx/bitcoind  /usr/bin/bitcoind
RUN  ln -s /hx/litecoind  /usr/bin/litecoind  
RUN  ln -s /hx/hcd  /usr/bin/hcd
RUN  ln -s /hx/hcwallet  /usr/bin/hcwallet
ENTRYPOINT ["/bin/bash", "-c", "/hx/start_third_chain.sh"]
