FROM zoowii/hxmiddleware_db

#
# docker metainfo
#
LABEL author="wens.wq"
LABEL description="docker file for hx environment"
LABEL version="1.0"

#
# data preparation
# 
RUN  mkdir -p /hx/crosschain_midware
COPY main_chain/crosschain_midware /hx/crosschain_midware
COPY main_chain/hx_node /hx
COPY main_chain/start.sh     /hx
COPY main_chain/genesis.json /hx
RUN  chmod +x  /hx/hx_node /hx/start.sh
RUN  ln -s /hx/hx_node  /usr/bin/hx_node

ENTRYPOINT ["/bin/bash", "-c", "/hx/start.sh"]




