version: '3'

services:
  python_web:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: 'yqr/python_web'

  chain_midware:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'yqr/midware'
    ports:
      - "80:80"
    links:
      - chaindb:chaindb
      - btc_wallet:btc_wallet
      - eth_wallet:eth_wallet
      - etp_wallet:etp_wallet
    depends_on:
      - chaindb
      - btc_wallet
      - eth_wallet
      - etp_wallet
    volumes:
      - ~/data/eth:/var/eth_data
      - ~/data/backup:/var/backup_keystore
    networks:
      app_net:
        ipv4_address: 172.28.8.2

  chaindb:
    image: 'mongo'
    entrypoint:
      - docker-entrypoint.sh
      - --auth
    ports:
      - "27017:27017"
    volumes:
      - ~/data/mongodb:/data/db
    networks:
      app_net:
        ipv4_address: 172.28.8.5

  btc_wallet:
    build:
      context: .
      dockerfile: Dockerfile.btc_wallet
    image: yqr/btc_wallet
    volumes:
      - ~/data/btc:/var/btc_data
    networks:
      app_net:
        ipv4_address: 172.28.8.3

  eth_wallet:
    build:
      context: .
      dockerfile: Dockerfile.eth_wallet
    image: 'yqr/eth_wallet'
    volumes:
      - ~/data/eth:/var/eth_data
    networks:
      app_net:
        ipv4_address: 172.28.8.4

  etp_wallet:
    build:
      context: .
      dockerfile: Dockerfile.etp_wallet
    image: 'yqr/etp_wallet'
    volumes:
      - ~/data/etp:/root/.metaverse
    networks:
      app_net:
        ipv4_address: 172.28.8.6

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.8.0/24